# Generated by Django 4.0.10 on 2023-04-19 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_shoppinglist_recipes_alter_shoppinglist_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favouriterecipes',
            old_name='recipes',
            new_name='recipe',
        ),
    ]
