# Generated by Django 4.0.10 on 2023-04-19 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_favouriterecipes_recipe_user_unique_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shoppinglist',
            old_name='recipes',
            new_name='recipe',
        ),
    ]
