# Generated by Django 4.0.10 on 2023-04-19 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_recipes_shoppinglist_recipe'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='shoppinglist',
            name='recipe_user_shoppinglist_unique',
        ),
        migrations.AddConstraint(
            model_name='shoppinglist',
            constraint=models.UniqueConstraint(fields=('recipe', 'user'), name='recipe_user_shoppinglist_unique'),
        ),
    ]
