version: '3.3'

services:
  db:
    container_name: db
    image: postgres:14.0-alpine
    volumes:
      - database:/var/lib/postgresql/data/
    env_file:
      - .env
    

  backend:
    container_name: app
    build:
      context: ../backend
      dockerfile: ../backend/Dockerfile
    restart: always
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/

    depends_on:
      - db
    env_file:
      - .env

  frontend:
    container_name: front
    build:
      context: ../frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend/:/app/result_build/
    depends_on:
      - backend

  nginx:
    container_name: proxy
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_value:/etc/nginx/html/static/
      - media_value:/etc/nginx/html/media/
    depends_on:
      - backend
      - frontend

volumes:
  database:
  static_value:
  media_value: