# Generated by Django 4.0.10 on 2023-04-26 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_ingredientsinrecipe_rename_recipetags_tagsinrecipe_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredientsinrecipe',
            old_name='ingredients',
            new_name='ingredient',
        ),
    ]
